services:
  rummagene-app:
    build: .
    platform: linux/amd64
    image: maayanlab/rummagene:0.3.23
    x-kubernetes:
      annotations:
        maayanlab.cloud/ingress: https://rummagene.k8s.maayanlab.cloud
    environment:
      - PUBLIC_URL=https://rummagene.k8s.maayanlab.cloud
      - DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@rummagene-postgres/$POSTGRES_DB
      - AUTHORIZATION_HEADER=$AUTHORIZATION_HEADER
      - NODE_ENV=production
      - NODE_OPTIONS=--max_old_space_size=4096
      - ENRICH_URL=http://rummagene-enrich:8000
      - NEXT_PUBLIC_GA_MEASUREMENT_ID=$NEXT_PUBLIC_GA_MEASUREMENT_ID
    ports:
      - 3000:3000
  rummagene-latest:
    image: maayanlab/proxy:1.2.16
    x-kubernetes:
      annotations:
        maayanlab.cloud/ingress: https://rummagene.k8s.maayanlab.cloud/latest.gmt
    ports:
    - 80
    environment:
    - "nginx_redirect_00=/latest.gmt https://s3.k8s.maayanlab.cloud/rummagene/database/latest/output-clean.gmt"
  rummagene-enrich:
    build: enrich
    platform: linux/amd64
    image: maayanlab/rummagene-enrich:0.6.0
    environment:
      - 'ROCKET_DATABASES={postgres={url="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@rummagene-postgres/${POSTGRES_DB}"}}'
    ports:
      - 8000:8000
  rummagene-postgres:
    build: db
    platform: linux/amd64
    image: maayanlab/rummagene-postgres:0.1.3
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - ENRICH_URL=http://rummagene-enrich:8000
    ports:
      - 5432:5432
    volumes:
      - rummagene-postgres:/var/lib/postgresql/data

  rummagene-bot:
    build: bot
    platform: linux/amd64
    image: maayanlab/rummagene-bot:0.3.5
    pull_policy: if_not_present
    deploy:
      replicas: 0
    x-kubernetes:
      restartPolicy: Never
      # 0 minute
      # 9 hour
      # * day of month
      # * month of year
      # 1 day of week (monday)
      cron: '0 9 * * 1'
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@rummagene-postgres:5432/${POSTGRES_DB}
      - ENRICH_URL=http://rummagene-enrich:8000
      - API_KEY
      - EMAIL
      - RCLONE_PATH
      - RCLONE_CONFIG_S3_TYPE
      - RCLONE_CONFIG_S3_PROVIDER
      - RCLONE_CONFIG_S3_ENDPOINT
      - RCLONE_CONFIG_S3_ACCESS_KEY_ID
      - RCLONE_CONFIG_S3_SECRET_ACCESS_KEY

volumes:
  rummagene-postgres:
    x-kubernetes:
      class: ceph-block
      size: 24G

x-kubernetes:
  name: rummagene
  namespace: rummagene
